//
// Xeto sys::UnitQuantity name = accepted QUDT quantity-kind local name(s)
// QUDT namespace: http://qudt.org/vocab/quantitykind/
// Multiple comma-separated names express QUDT taxonomy alternatives.
//

acceleration=Acceleration
angularAcceleration=AngularAcceleration
angularMomentum=AngularMomentum
angularVelocity=AngularVelocity,RotationalVelocity
apparentEnergy=Energy
apparentPower=ComplexPower
area=Area
bytes=InformationEntropy
capacitance=Capacitance
coolingEfficiency=DimensionlessRatio
currency=Currency
density=Density
electricCharge=ElectricCharge
electricConductance=Conductance
electricCurrent=ElectricCurrent
electricCurrentDensity=ElectricCurrentDensity
electricFieldStrength=ElectricFieldStrength
electricPotential=ElectricPotential
electricResistance=Resistance
electricalConductivity=Conductivity
electricalResistivity=Resistivity
electromagneticMoment=MagneticMoment
energy=Energy,MomentOfForce,Torque
energyByArea=EnergyPerArea
energyByVolume=EnergyDensity,Unknown
specificEnthalpy=SpecificEnergy
entropy=Entropy,EnergyPerTemperature,HeatCapacity
force=Force
frequency=Frequency
grammage=MassPerArea
heatingRate=TemperaturePerTime
illuminance=LuminousFluxPerArea
inductance=Inductance
irradiance=PowerPerArea
length=Length
luminance=Luminance
luminousFlux=LuminousFlux
luminousIntensity=LuminousIntensity
magneticFieldStrength=MagneticFieldStrength_H
magneticFlux=MagneticFlux
magneticFluxDensity=MagneticFluxDensity
mass=Mass
massFlow=MassFlowRate
momentum=Momentum
power=Power
powerByArea=PowerPerArea
pressure=ForcePerArea
reactiveEnergy=Energy
reactivePower=ReactivePower
specificEntropy=SpecificEntropy
surfaceTension=ForcePerLength
temperature=Temperature
temperatureDifferential=Temperature
thermalConductivity=ThermalConductivity
time=Time
velocity=Velocity,Speed
volume=Volume
volumetricFlow=VolumeFlowRate
